version: '3.8'

services:
  express-mongo-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express_mongo_app
    ports:
      - "3001:3001"
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      PORT: ${PORT}
      APP_PORT: ${APP_PORT}
      KAFKA_ID: ${KAFKA_ID}
      KAFKA_HOST: ${KAFKA_HOST}   # should be kafka:9092 for internal networking
    depends_on:
      - mongodb
      - zookeeper
    restart: always
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    restart: always
    networks:
      - app-network

  mongodb:
    image: mongo:8.0.10-rc0
    container_name: mongo_db
    ports:
      - "${PORT}:${PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    container_name: mongo_ui
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASS}
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    restart: always
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
