version: '3.8'

services:
  express-mongo-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express_mongo_app
    ports:
      - "3001:3001"
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      PORT: ${PORT}
      APP_PORT: ${APP_PORT}
      KAFKA_ID: ${KAFKA_ID}
      KAFKA_HOST: ${KAFKA_HOST}   # should be kafka:9092 for internal networking
    depends_on:
      - mongodb
    restart: always
    networks:
      - space-be_app-network

  mongodb:
    image: mongo:8.0.10-rc0
    container_name: mongo_db
    ports:
      - "${PORT}:${PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - space-be_app-network

volumes:
  mongo_data:

networks:
  space-be_app-network:
    external: true
